name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t eleventy-blog-image .
      - name: Build site
        run: docker run -t --rm -v `pwd`/_site:/app/_site:Z -w /app eleventy-blog-image --output=_site
      - name: Rename `_site` to `docs`
        run: mv ./_site ./docs
      - name: Push `docs` to `gh-pages` branch
        run: |
          git config --global user.name 'Libor Bakajsa'
          git config --global user.email 'lbakajsa@gmail.com'
          git checkout -b gh-pages
          git add ./docs
          git commit -m "Regenerate site"
          git push origin gh-pages:gh-pages --force
